# Generated by Django 3.1.5 on 2021-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
