# Generated by Django 3.1.5 on 2021-01-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20210120_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='img_url',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
