# Generated by Django 3.1.5 on 2021-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0007_auto_20210201_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shop_id',
            field=models.UUIDField(),
        ),
    ]
